[package]
name = "soroban-risc0-cli"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rx.workspace = true
rx.features = [
  "rx-profile-cli",
]

[[bin]]
name = "soroban-risc0"
path = "src/main.rs"
