[package]
name = "soroban-risc0"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
soroban-sdk.workspace = true
risc0-zkvm.workspace = true
risc0-zkvm.default-features = false
